version: '3.8'

services:
  # Наша база данных
  db:
    image: postgres:15
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'     # Не даем одному app съесть больше пол-ядра
          memory: 128M     # Ограничим память
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Один файл лога не больше 10 МБ
        max-file: "3"      # Храним только 3 последних файла
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Наше Python-приложение
  app:
  #  build: ./app
    image: cr.yandex/${YC_REGISTRY_ID}/my-app:${APP_TAG:-latest}
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'     # Не даем одному app съесть больше пол-ядра
          memory: 128M     # Ограничим память
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Один файл лога не больше 10 МБ
        max-file: "3"      # Храним только 3 последних файла
    env_file: .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s    # Проверять каждые 30 секунд
      timeout: 10s     # Ждать ответа 10 секунд
      retries: 3       # Если 3 раза упал — значит "unhealthy"
      start_period: 10s # Дать 10 секунд на "прогрев" при старте

  # Наш веб-сервер (лицо проекта)
  nginx:
    image: nginx:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'     # Не даем одному app съесть больше пол-ядра
          memory: 128M     # Ограничим память
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Один файл лога не больше 10 МБ
        max-file: "3"      # Храним только 3 последних файла
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  postgres_data:
